#+TITLE: twtxt

[[https://melpa.org/#/twtxt][https://melpa.org/packages/twtxt-badge.svg]]
[[https://img.shields.io/badge/GNU%20Emacs-25.1-b48ead.svg]]

A twtxt client for Emacs

* Install

** Melpa

~twtxt~ is available from
Melpa. After [[https://melpa.org/#/getting-started][setting up]] Melpa
as a repository and update the local package list, you can install
~twtxt~ and its dependencies using ~M-x package-install twtxt~.

** Manually

Add twtxt to your ~load-path~ and require. Something like:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "path/to/twtxt/")
  (require 'twtxt)
#+END_SRC

* Setup

#+BEGIN_SRC emacs-lisp
    (setq twtxt-file "~/my/twtxt") ;; Path to twtxt file. Default "~/twtxt"
#+END_SRC

If you don't have a twtxt file yet, you can create one using this template:

#+BEGIN_SRC text
# Learn more about twtxt:
#     https://twtxt.readthedocs.io/en/stable/
#
# nick = Foo
# url = https://example.org/twtxt.txt
# avatar = https://example.org/avatar.jpg
# description = I'm a hacker
#+END_SRC

* Manage followers

You should add your followers to the ~twtxt-file~.

#+BEGIN_SRC text
# Learn more about twtxt:
#     https://twtxt.readthedocs.io/en/stable/
#
# nick = Foo
#
# ...
#
# follower = user https://example.org/twtxt.txt
# follower = user2 https://example-2.org/twtxt.txt
#+END_SRC

You can read more about the ~threads~ specification in the [[https://twtxt.dev/#mentions-and-threads][extension]].

* replies

optionally, if you want to replicate a post, you need to install the following unix tools:

- ~b2sum~
- ~awk~
- ~xxd~
- ~base32~
- ~tr~
- ~tail~

otherwise you will only be able to replicate existing threads, not create them.

you can read more about the ~follower~ specification in the [[https://twtxt.dev/exts/metadata.html#follow][extension]].

* Usage

View your timeline

~M-x twtxt-timeline~

| Key | Action |
|------|--------|
| ~n~ | Next post |
| ~p~ | Previous post |
| ~c~ | New post |
| ~g~ | Fetch posts |
| ~r~ | Reply to post |
| ~t~ | Go to thread |
| ~P~ | Go to my profile |
| ~q~ | Quit |


Post a status update

~M-x twtxt-post~

| Key | Action |
|------|--------|
| ~C-c C-c~ | Post tweet |
| ~C-c C-m~ | Add mention |
| ~C-c C-k~ | Cancel tweet |

* Optional configuration

Set the twtxts per page:

#+BEGIN_SRC emacs-lisp
  (setq twtxt--twtxts-per-page 10)
#+END_SRC

* Hooks

You can use the following hooks to perform additional actions automatically:

| Name | Description |
|------|------------|
| ~twtxt-post-tweet-hook~ | Hook run after posting a tweet. |
| ~twtxt-after-fetch-posts-hook~ | Hook run after fetching posts. |

For example, upload your twtxt file to a server or execute other commands. Configure it as follows:

#+BEGIN_SRC emacs-lisp
  ;; Example: Upload twtxt file to a remote server using scp: scp twtxt.txt user@server:/your/path/twtxt.txt
  (add-hook 'twtxt-post-tweet-hook (lambda () (call-process-shell-command (format "scp %s %s"
  									 twtxt-file
  									 "user@server:/your/path/twtxt.txt"
  									 ) nil 0)))
#+END_SRC
